### ISSUE TITLE
AttributeError: module 'tensorflow.contrib.estimator' has no attribute 'stop_if_no_decrease_hook'

### ISSUE THREAD

**Issue by Biaocsu** [EOA-AILab/NER-Chinese#1]
你好，我用tensorflow版本为1.14.0，运行你的代码出现
Traceback (most recent call last):
  File "bert_ner_api.py", line 47, in <module>
    train_api()
  File "bert_ner_api.py", line 21, in train_api
    train(args)
  File "/home/desktop/KG/NER-Chinese/bert_ner/bert_ner/bert_base/train/bert_lstm_ner.py", line 677, in train
    early_stopping_hook = tf.contrib.estimator.stop_if_no_decrease_hook(
AttributeError: module 'tensorflow.contrib.estimator' has no attribute 'stop_if_no_decrease_hook'
麻烦帮解决一下

**Comment by EOA-AILab** [comment]
@Biaocsu 你好！你的这个问题是由于tensorflow的新版本所引起的。tensorflow-gpu 1.14.0版本通过import tensorflow.estimator.experimental.stop_if_no_decrease_hook进行调用。建议尝试换成tensorflow-gpu 1.13.1版本。

**Comment by Biaocsu** [comment]
@EOA-AILab 嗯嗯，多谢。期待你bert模型速度优化结果

**Comment by whao1011** [comment]
> tensorflow -gpu 1.14.0版本通过import tensorflow.estimator.experimental.stop_if_no_decrease_hook进行尝试。建议尝试换成tensorflow-gpu 1.13.1版本。@ Biaocsu你好！你的这个问题是由于tensorflow的新版本所引起的。

@ EOA-AILab你好！我换成了tf 1.13.1的版本怎么tf.estimator却报红找不到了
